#docker-compose.yml (Base)
version: '3.4'
services:
  cocktailmaker:
    image: cocktailmaker:${TAG:-latest}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
